version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:      
      MYSQL_ROOT_PASSWORD: 'password123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      #- PMA_ARBITRARY=1
      - PMA_HOST=db
      - UPLOAD_LIMIT=2G
      - MAX_EXECUTION_TIME=900
      - MEMORY_LIMIT=1.5G
    depends_on:
      - db
